VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
VIAL_INSECURE = yes

EXTRAFLAGS += -flto

# squeeze size
LTO_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

# sm_td
SRC += sm_td.c
DEFERRED_EXEC_ENABLE = yes
